### ISSUE TITLE
[DOC] - Readme file enhancement

### ISSUE THREAD

**Issue by Susmita-Dey** [Semalab/developer-skills-matrix-discord-bot#15]
### What is incorrect in the documentation?

The README file neither contains any description of the bot nor about the project which could help newbies to contribute to this repository.

### What should that text say?

The text should say:
- A short description about the bot
- A logo of sema/oswc
- A line redirecting to the LICENSE file
- A line to check for the CONTRIBUTING file
- Thank You section for the Contributors having badge
- Some emojis to encourage the contributors along with the above sections.

**Comment by AnujSsStw** [comment]
hey can you say which fields are currently required like there is **About The Project**, then **Installation**, maybe **Usage** and **License**.
Any other?

**Comment by AnujSsStw** [comment]
for now you can check this out https://github.com/AnujSsStw/readme-testing/blob/main/README.md
If you have anythoughts feel free to let me know.

**Comment by MrHerbalizer** [comment]
Hi, please check this file :
https://github.com/MrHerbalizer/developer-rubric-discord-bot/blob/main/README.md
Have added a license badge. Instead of contributor's name with hyperlink, have added an image, which ideally should update daily (fingers crossed). Have added some info.
Do share if you seek any changes/updates in the file.

**Comment by nhcarrigan** [comment]
PRs are welcome - we encourage you to open draft PRs if you have work that is not ready to merge but needs a second set of eyes. 😁

**Comment by MrHerbalizer** [comment]
Gosh..!!  Opened a PR instead of a draft PR. Please excuse my naivety..:/
