### ISSUE TITLE
[OTHER] - Repo / project renaming?

### ISSUE THREAD

**Issue by mattvanitallie-sema** [Semalab/developer-skills-matrix-discord-bot#20]
### What would you like to share?

so....

someone, i won't say who but his name rhymes with "sat tan eatily";0, was not precise about terminology in setting up this project.

We are calling this the "Developer Skill Matrix" to the outside world.

How hard would it be to change the names of the projects from Rubric to Matrix?

How good/bad does "rubric" sound to you?

Does it sound like a good idea to rename these repos in light of the above?

I am sorry and will be more careful next time.

**Comment by nhcarrigan** [comment]
The only concern with renaming repositories is that any active contributors will have to update their upstreams.

Thankfully, the projects are new enough that we should be okay. I will go ahead and rename these.

**Comment by mattvanitallie** [comment]
Grateful. Thank you.

**Comment by Panquesito7** [comment]
> The only concern with renaming repositories is that any active contributors will have to update their upstreams.

I think when a repository's name is updated, it doesn't affect when pushing. Not sure, though.
